# Site
title: "OLS"
description: >
  A mentoring & training program for Open Science ambassadors
logo: ''
email: team@we-are-ols.org
finance_email: financemanagement@we-are-ols.org
repository: open-life-science/open-life-science.github.io
twitter: openlifesci
gitter: open-life-sci/community
url: https://openlifesci.org/
announcement_list: https://groups.google.com/g/ols-news
youtube: https://www.youtube.com/channel/UCs12-ZgnDJOWIWN3Vo1XHXA/

includes_dir: .
markdown: kramdown

collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
  consulting:
    output: true
    permalink: /consulting/:path/

toc:
  min_level: 1 # default: 1
  max_level: 3 # default: 6
  list_class: menu-list

plugins:
  - jekyll-github-metadata
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-spaceship
  - jekyll-redirect-from
  - jekyll-toc
